export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const USERDATA_FETCHED = 'USERDATA_FETCHED';
export const LOGOUT = 'LOGOUT';
