export const SEARCH_MEMBERS = 'SEARCH_MEMBERS';
export const FETCH_MEMBERS = 'FETCH_MEMBERS';
export const MEMBERS_FETCHED = 'MEMBERS_FETCHED';
export const FILTER_CIRCLES = 'FILTER_CIRCLES';
export const MEMBER_DELETED = 'MEMBER_DELETED';
export const CREATE_MEMBER = 'CREATE_MEMBER';
