export const SET_NAV_VISIBLE = 'SET_NAV_VISIBLE';
export const SET_NAV_INVISIBLE = 'SET_NAV_INVISIBLE';
export const SET_NAV_EXPANDED = 'SET_NAV_EXPANDED';
export const SET_NAV_COLLAPSED = 'SET_NAV_COLLAPSED';
export const UPDATE_NAV_USERDATA = 'UPDATE_NAV_USERDATA';
