export const NEWS_ARTICLE_FETCHED = 'NEWS_ARTICLE_FETCHED';
export const FETCH_NEWS_ARTICLES = 'FETCH_NEWS_ARTICLES';
export const NEWS_ARTICLES_FETCHED = 'NEWS_ARTICLES_FETCHED';
export const NEWS_ARTICLE_DELETED = 'NEWS_ARTICLE_DELETED';
export const CREATE_NEWS_ARTICLE = 'CREATE_NEWS_ARTICLE';
export const PUT_NEWS_ARTICLE = 'PUT_NEWS_ARTICLE';
export const SEARCH_NEWS_ARTICLES = 'SEARCH_NEWS_ARTICLES';
