export const FETCH_PROFILE = 'FETCH_PROFILE';
export const PROFILE_USER_FETCHED = 'PROFILE_USER_FETCHED';
export const PROFILE_COMPLOC_FETCHED = 'PROFILE_COMPLOC_FETCHED';
export const PROFILE_COMP_FETCHED = 'PROFILE_COMP_FETCHED';
export const PUT_PROFILE = 'PUT_PROFILE';
